package ar.com.modelo;
// Generated 04/08/2018 20:08:18 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusUser generated by hbm2java
 */
@Entity
@Table(name = "status_user", catalog = "baserest")
public class StatusUser implements java.io.Serializable {

	private Integer id;
	private int status;

	public StatusUser() {
	}

	public StatusUser(int status) {
		super();
		this.status = status;
	}

	public StatusUser(Integer id, int status) {
		super();
		this.id = id;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
